# Generated by Django 5.2.17 on 2026-09-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('record_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recorded_on', models.DateField()),
                ('record_kind', models.CharField(choices=[('CHECKUP', 'Checkup'), ('ILLNESS', 'Illness'), ('INJURY', 'Injury'), ('SURGERY', 'Surgery'), ('DIAGNOSIS', 'Diagnosis'), ('FOLLOW_UP', 'Follow-up'), ('EMERGENCY', 'Emergency'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('care_notes', models.TextField(blank=True, null=True)),
                ('vet_name', models.CharField(blank=True, max_length=150, null=True)),
                ('attachment', models.FileField(blank=True, db_column='attachment_url', max_length=500, null=True, upload_to='medical_records/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'medical_records',
                'ordering': ['-recorded_on', '-record_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medication_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=150)),
                ('dose', models.CharField(max_length=100)),
                ('route', models.CharField(blank=True, max_length=100, null=True)),
                ('frequency', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'medications',
                'ordering': ['-start_date', '-medication_id'],
                'managed': False,
            },
        ),
    ]
