# Generated by Django 5.2.17 on 2026-09-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('vaccination_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(max_length=150)),
                ('dose_label', models.CharField(blank=True, max_length=100, null=True)),
                ('administered_on', models.DateField()),
                ('next_due_on', models.DateField(blank=True, null=True)),
                ('clinic_name', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vaccinations',
                'ordering': ['-administered_on', '-vaccination_id'],
                'managed': False,
            },
        ),
    ]
