# Generated by Django 5.2.17 on 2026-09-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0002_vaccination'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthRecord',
            fields=[
                ('growth_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('measured_on', models.DateField()),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('milestone', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'growth_records',
                'ordering': ['-measured_on', '-growth_id'],
                'managed': False,
            },
        ),
    ]
