# Generated by Django 5.2.17 on 2026-09-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0003_growthrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareReminder',
            fields=[
                ('reminder_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('reminder_kind', models.CharField(choices=[('VET_APPOINTMENT', 'Vet appointment'), ('MEDICATION', 'Medication'), ('VACCINATION', 'Vaccination'), ('GROOMING', 'Grooming'), ('DEWORMING', 'Deworming'), ('FEEDING', 'Feeding'), ('OTHER', 'Other')], max_length=30)),
                ('remind_at', models.DateTimeField()),
                ('details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'care_reminders',
                'ordering': ['remind_at', 'reminder_id'],
                'managed': False,
            },
        ),
    ]
