# Generated by Django 5.2.17 on 2026-09-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetReport',
            fields=[
                ('report_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('LOST', 'Lost'), ('FOUND', 'Found')], max_length=10)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('incident_at', models.DateTimeField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, db_column='photo_url', max_length=500, null=True, upload_to='pet_reports/')),
                ('report_status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pet_reports',
                'ordering': ['-created_at', '-report_id'],
                'managed': False,
            },
        ),
    ]
