# Generated by Django 5.2.17 on 2026-09-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionListing',
            fields=[
                ('listing_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('listing_status', models.CharField(choices=[('ACTIVE', 'Active'), ('ADOPTED', 'Adopted'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('listed_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'adoption_listings',
                'ordering': ['-listed_at', '-listing_id'],
                'managed': False,
            },
        ),
    ]
